version: 1
formatters:
  livres_form:
    format: '%(asctime)s - %(module)s - %(funcName)s - %(levelname)s - %(message)s'
    datefmt: '%d/%m/%Y %H:%M'
  transactions_form:
    format: '%(name)s - %(levelname)s - %(message)s'
handlers:
  stream_handler_transactions:
    class: logging.StreamHandler
    formatter: transactions_form
    stream: ext://sys.stdout
  stream_handler_livres:
    class: logging.StreamHandler
    formatter: livres_form
    stream: ext://sys.stdout
loggers:
  livres_logger:
    level: INFO
    handlers: [stream_handler_livres]
  transactions_logger:
    level: WARNING
    handlers: [stream_handler_transactions]
